from __future__ import annotations

CARD_SUMMARIES: dict[str, str] = {
    "w1-python-basics": "Python runs top to bottom, one logical line at a time. Comments do not execute, and indentation decides which statements belong to the same block.",
    "w1-objects-and-names": "Objects have identity, type, and value. Names bind to objects; rebinding changes the name, while mutation only matters for mutable objects.",
    "w1-operators-and-truth": "Know arithmetic, comparison, and boolean precedence. Distinguish `/` vs `//`, `**` vs `^`, and trace truth values with `not`, `and`, and `or`.",
    "w1-sequences-and-access": "Use `seq[start:stop:step]` with stop excluded. Negative indices count from the end, and `range(start, stop, step)` follows the same stop-excluded rule.",
    "w1-functions-and-imports": "`import x` keeps the module name, `from x import y` brings `y` into scope, and `as` renames. Call functions with `()`, and keep `print` separate from returned values.",
    "w2-dictionaries-and-mappings": "Dicts map unique immutable keys to values. `key in d` checks keys, `d[key]` looks up a value, and `.items()` gives `(key, value)` pairs for loops.",
    "w2-lists-and-sets": "Lists keep order and duplicates; sets keep unique elements with no reliable order. Know which operations mutate in place and which build a new object.",
    "w2-conditions": "Combine comparisons with `and`, `or`, and `not`, and add parentheses whenever precedence is easy to misread. Remember conditional expressions use `x if cond else y`.",
    "w2-loops": "Trace loop variables carefully: `for` iterates items, `range` generates values, `enumerate` adds indices, and `zip` walks sequences together.",
    "w2-conversion-and-truthiness": "Use explicit conversion functions instead of expecting Python to coerce types. Empty containers, `0`, `0.0`, and `''` are falsy; most other values are truthy.",
    "w3-defining-and-calling-functions": "Define functions with `def name(params):` and call them with `()`. Separate method calls from standalone functions, and know which operations mutate versus return.",
    "w3-return-behavior": "`return` ends the function and gives a value back to the caller. If no `return` runs, the function returns `None`, and commas create tuples.",
    "w3-scope": "Assignment inside a function creates a local name unless `global` or `nonlocal` says otherwise. Reading a local before assignment raises `UnboundLocalError`.",
    "w3-arguments": "Match arguments by position, keyword, defaults, `*args`, and `**kwargs`. Avoid mutable default traps by using `None` and creating the list or dict inside the function.",
    "w3-higher-order-patterns": "`lambda`, `map`, `filter`, `reduce`, and `sorted(key=...)` all apply a function to values. Be clear about whether the result is lazy, filtered, aggregated, or newly sorted.",
    "w4-string-fundamentals": "Strings are immutable, so methods return new strings instead of changing the original in place. Know quote choices, escapes like `\\n` and `\\t`, and how slicing rebuilds a new string.",
    "w4-string-operations-and-methods": "Trace string slicing, search, replacement, splitting, joining, and stripping. Compare `.find` versus `.index`, and remember `join` is called on the separator.",
    "w4-string-formatting": "Use f-strings to embed expressions directly in text. Add format specs after `:` for width, alignment, or precision such as `{n:03d}` and `{x:.2f}`.",
    "w4-oop-fundamentals": "A class defines attributes and methods; `__init__` runs when you create an object and stores instance data on `self`.",
    "w4-error-handling": "`try/except` catches specific exceptions, and `raise` creates or rethrows one. Keep the protected code small enough that you know what can fail.",
    "w5-pandas-core-structures": "A Series is 1D labeled data; a DataFrame is a 2D labeled table. Know common constructors and whether an operation returns a Series or a DataFrame.",
    "w5-inspecting-and-selecting-data": "Use `head`, `tail`, and `describe` to inspect quickly. Use `.loc` for labels, `.iloc` for integer positions, and boolean masks for row filtering.",
    "w5-working-with-values": "Sort, fill or drop missing values, compare or broadcast columns, and apply vectorized string or Series methods. Prefer vectorized operations before row-wise `apply`.",
    "w5-combining-data": "`concat` stacks along rows or columns, `merge` joins on keys, and `groupby` splits data before aggregation.",
    "w6-comprehensions": "Comprehensions build new lists, sets, or dicts from a compact loop expression. Know the order of `for` and `if`, and use them for short transformations.",
    "w6-generators-and-iterators": "Iterables produce iterators, iterators yield one value at a time with `next`, and generator functions or comprehensions create lazy sequences.",
    "w6-datetime": "Use `datetime.now()` for current time, `strftime` to format, `strptime` to parse, and `timedelta` for date arithmetic.",
}

TEXT_REWRITES: dict[str, str] = {
    "Every object has exactly one unique id (cannot change), exactly one type (cannot change), and exactly one value. The type defines what value can be stored and whether the value is mutable or immutable. An object can have zero, one, or more names bound to it. A name can only refer to one object at any time.": "Each object has identity, type, and value. Names bind to objects; rebinding changes the name, while in-place changes only affect mutable objects.",
    "Immutable: int, float, str, bool, tuple. Mutable: list, dict, set. The value of a mutable object CAN be changed in-place. The value of an immutable object CANNOT be changed — a new object must be created.": "Immutable types like `int`, `float`, `str`, and `tuple` cannot change in place. Mutable types like `list`, `dict`, and `set` can be changed through the same object.",
    "Python creates a new object with the value on the right, infers type from the value, then binds the name on the left to that object.": "Assignment binds the left-hand name to the object produced on the right-hand side.",
    "int, float, str, bool, tuple, list, dict, set": "Core built-in types: `int`, `float`, `str`, `bool`, `tuple`, `list`, `dict`, `set`.",
    "Forward: 0, 1, 2, ... len-1. Backward: -1 (last), -2 (second to last), ..., -len (first). l1[0] == l1[-len(l1)]": "Negative indices count from the end: `seq[-1]` is last and `seq[-len(seq)]` is first.",
    "range(start, stop, step). `start` defaults to 0 and `step` defaults to 1. Stop is excluded. Same stop-excluded rule as slicing.": "`range(start, stop, step)` excludes `stop`; defaults are `start=0` and `step=1`, just like slicing excludes the stop index.",
    "Multiple import styles. 'import X' makes X available. 'import X as Y' renames. 'from X import Z' brings Z directly into namespace. 'from X import Z as W' renames. Once you use 'as', the original name is no longer accessible.": "`import x` keeps the module name, `import x as y` renames it, and `from x import z` brings `z` into scope directly.",
    "Print is a function and tells Python to output the argument (that what is between the brackets after the function name) on your screen A function is a grouping of code that can perform a certain task and can be re-used ;": "Use `print(...)` to display a value. A function groups reusable code and may also return a value to its caller.",
    "Sets of key:value pairs. Keys must be unique and immutable (hashable). Dictionaries are unordered for equality ({1:1,2:2}=={2:2,1:1} is True). Cannot be sorted. You can check membership with 'in' — this checks KEYS only. Keys() gives key sequence, values() gives value sequence, items() gives tuples.": "Dicts map unique immutable keys to values. `key in d` checks keys, and equality ignores insertion order.",
    ".keys() → key sequence. .values() → value sequence. .items() → sequence of (key, value) tuples. 'for key in dict' is the same as 'for key in dict.keys()'.": "Use `.keys()`, `.values()`, and `.items()` for dictionary views; looping over a dict directly gives keys.",
    "def keyword, function name, parameters in parentheses, colon, indented body. Call with round brackets (). Using [] gives TypeError 'not subscriptable'. Using [] on a list with () gives TypeError 'not callable'.": "Define with `def name(params):` and call with `()`. `f[3]` tries to index, while `lst(0)` tries to call a list and raises `TypeError`.",
    "Methods are functions attached to objects. Calling obj.method() is equivalent to Class.method(obj). For mutable objects: some methods CHANGE the object (e.g. list.sort()), some RETURN a value (e.g. list.index()). For immutable objects: methods always return a new value (can't change the object itself).": "Methods are functions attached to objects. Some mutate the object in place, while others return a value; string methods always return a new string.",
    "Strings in Python are immutable, meaning they cannot be changed in place. Methods like upper() or replace() return a new string object rather than modifying the original.": "Strings are immutable: methods like `.upper()` and `.replace()` return a new string, so assign the result back if you want the change to stick.",
    "Special characters like newlines (\\n), tabs (\\t), or literal quotes can be included using the backslash (\\).": "Escape sequences: `\\n` newline, `\\t` tab, and `\\'` or `\\\"` for literal quotes.",
    "A class is a blueprint. The __init__ method is the constructor called automatically when a new object is created to initialize attributes.": "A class defines methods and attribute layout; `__init__` runs when you create an object and stores instance data on `self`.",
    "In class methods, 'self' refers to the specific instance of the object. It must be the first parameter of any instance method.": "`self` refers to the current instance, so instance methods read and write data through `self.attr`.",
    "Instance attributes (self.x) are unique to each object. Class attributes are defined outside methods and shared by all instances of the class.": "`self.x` is per object; a class attribute is shared until an instance shadows it with its own value.",
    "A one-dimensional labeled array. If no index is provided, it defaults to integers starting from 0.": "A `Series` is 1D labeled data; without an explicit index it uses `0, 1, 2, ...`.",
    "A two-dimensional tabular data structure. Most commonly created from a dictionary where keys are column names and values are lists.": "A `DataFrame` is a 2D table, often created from a dict of column names to lists.",
    "A specialized index for dates. Elements have attributes like .year, .month, and .day.": "Datetime indexes support attributes like `.year`, `.month`, and `.day` for date-based filtering.",
    "datetime.now() retrieves the current local time. timestamp() returns the seconds since the Unix Epoch (Jan 1, 1970).": "`datetime.now()` gives the current local datetime; `.timestamp()` converts it to seconds since the Unix epoch.",
    "Formats a datetime object into a readable string using format codes (e.g., %Y for 4-digit year, %m for month).": "`strftime` formats a datetime into text using codes like `%Y`, `%m`, and `%d`.",
    "Parses a string into a datetime object based on a provided format template.": "`strptime` parses text into a datetime using the format template you provide.",
    "Timedelta objects represent durations. Subtracting two datetimes creates a timedelta; adding a timedelta to a datetime shifts the date.": "`timedelta` represents a duration. Datetime subtraction creates one, and adding one shifts the date or time.",
    "Datetime objects are immutable. The replace() method creates a new datetime object with specific attributes changed.": "Datetime objects are immutable; `.replace(...)` returns a new datetime with selected parts changed.",
}

TITLE_REWRITES: dict[str, str] = {
    "imports": "Import forms and aliases",
    "dictionaries": "Dictionary creation and lookup",
    "strings_quotes": "String quotes and escaping",
    "conditions": "Condition result",
    "augmented_operators": "Augmented assignment (`+=`)",
    "range examples": "range() output patterns",
}

TOPIC_EXCLUDES: dict[str, tuple[str, ...]] = {
    "w4-string-fundamentals": ("dataframe", "series", ".loc", ".iloc", "pandas", "df["),
    "w4-string-operations-and-methods": ("dataframe", "series", ".loc", ".iloc", "pandas", "df["),
    "w4-string-formatting": ("dataframe", "series", ".loc", ".iloc", "pandas", "df["),
    "w4-oop-fundamentals": (".loc", ".iloc", "pandas", "series", "dataframe", "map(", "lambda"),
    "w5-pandas-core-structures": ("class ", "__init__", " self", "rectangle", "flight", "vehicle"),
    "w3-defining-and-calling-functions": ("dataframe", ".loc", ".iloc", "series", "pandas"),
}
