from __future__ import annotations

from typing import Any


MANUAL_SNIPPETS_PART2: list[dict[str, Any]] = [
    {
        "id": "manual-pandas-values",
        "title": "Pandas Filtering, Sorting, and Lambda Patterns",
        "snippet_type": "general_snippet",
        "parent_topic": "Pandas Data Work",
        "main_topic": "Working With Values",
        "main_week": 5,
        "related_topics": ["Inspecting and Selecting Data", "Pandas Core Structures"],
        "related_weeks": [5],
        "importance_score": 7,
        "importance_bucket": "highest_value",
        "score_source": "manual_bootstrap",
        "manual_score_reason": "Supports repeated weak questions on filtering, sorting, derived columns, map/apply, and lambda usage.",
        "pieces": [
            {
                "id": "manual-pandas-values-table",
                "piece_type": "reference_table",
                "title": "Value transformation patterns",
                "content": {
                    "headers": ["Goal", "Pattern", "Example"],
                    "rows": [
                        ["filter rows", "df[df['A'] > 0]", "df[df['score'] >= 6]"],
                        ["sort by values", "df.sort_values(by='A')", "df.sort_values(by='score', ascending=False)"],
                        ["sort by index", "df.sort_index()", "df.sort_index(ascending=False)"],
                        ["new column", "df['C'] = df['A'] + df['B']", "df['total'] = df['x'] + df['y']"],
                        ["series map", "s.map(lambda x: ...)", "df['A'].map(lambda x: x + 1)"],
                        ["row apply", "df.apply(lambda row: ..., axis=1)", "df.apply(lambda row: row['A'] + row['B'], axis=1)"],
                        ["membership filter", "s.isin(vals)", "df[df['city'].isin(['A', 'B'])]"],
                    ],
                },
                "selectable": True,
            },
            {
                "id": "manual-pandas-values-code",
                "piece_type": "code_example",
                "title": "Column math plus filter",
                "content": {
                    "code": "df['total'] = df['A'] + df['B']\nresult = df[df['total'] > 10]",
                    "note": "Derived columns are assigned first, then reused in later filters or selections.",
                },
                "selectable": True,
            },
        ],
    },
    {
        "id": "manual-datetime-parse-format",
        "title": "Datetime Parse and Format Cheat Sheet",
        "snippet_type": "general_snippet",
        "parent_topic": "Datetime and Time Logic",
        "main_topic": "Datetime Parsing and Formatting",
        "main_week": 6,
        "related_topics": ["Datetime Arithmetic and Comparisons"],
        "related_weeks": [6],
        "importance_score": 10,
        "importance_bucket": "highest_value",
        "score_source": "manual_bootstrap",
        "manual_score_reason": "Core datetime reference for recurring `strptime` and `strftime` questions.",
        "pieces": [
            {
                "id": "manual-datetime-parse-format-table",
                "piece_type": "reference_table",
                "title": "Datetime parse vs format",
                "content": {
                    "headers": ["Goal", "Pattern", "Example"],
                    "rows": [
                        ["parse text", "datetime.strptime(text, fmt)", "datetime.strptime('05.12.2023', '%m.%d.%Y')"],
                        ["format datetime", "dt.strftime(fmt)", "dt.strftime('%Y-%m-%d')"],
                        ["current time", "datetime.now()", "datetime.now()"],
                        ["access parts", "dt.year / dt.month / dt.day", "dt.year"],
                    ],
                },
                "selectable": True,
            },
            {
                "id": "manual-datetime-parse-format-explain",
                "piece_type": "explanation",
                "title": "Key distinction",
                "content": {
                    "text": "`strptime` turns text into a datetime object. `strftime` turns a datetime object into text. Do arithmetic before formatting back to a string.",
                },
                "selectable": True,
            },
        ],
    },
    {
        "id": "manual-datetime-arithmetic",
        "title": "Datetime Arithmetic and Comparisons",
        "snippet_type": "general_snippet",
        "parent_topic": "Datetime and Time Logic",
        "main_topic": "Datetime Arithmetic and Comparisons",
        "main_week": 6,
        "related_topics": ["Datetime Parsing and Formatting"],
        "related_weeks": [6],
        "importance_score": 7,
        "importance_bucket": "highest_value",
        "score_source": "manual_bootstrap",
        "manual_score_reason": "Fills object-vs-string and timedelta reasoning gaps that remain after parse/format syntax is known.",
        "pieces": [
            {
                "id": "manual-datetime-arithmetic-table",
                "piece_type": "reference_table",
                "title": "Datetime arithmetic patterns",
                "content": {
                    "headers": ["Goal", "Pattern", "Example"],
                    "rows": [
                        ["add days", "dt + timedelta(days=n)", "day + timedelta(days=7)"],
                        ["subtract dates", "dt2 - dt1", "end - start"],
                        ["compare dates", "dt1 < dt2", "start < end"],
                        ["replace part", "dt.replace(year=...)", "dt.replace(year=2026)"],
                    ],
                },
                "selectable": True,
            },
            {
                "id": "manual-datetime-arithmetic-code",
                "piece_type": "code_example",
                "title": "Do math before formatting",
                "content": {
                    "code": "from datetime import datetime, timedelta\nstart = datetime.strptime('2024-05-20', '%Y-%m-%d')\nnext_week = start + timedelta(days=7)\nprint(next_week.strftime('%Y-%m-%d'))",
                    "note": "Once you call `strftime`, you have text, not a datetime object.",
                },
                "selectable": True,
            },
        ],
    },
    {
        "id": "manual-oop-fundamentals",
        "title": "OOP Fundamentals: self, __init__, Attributes, and Defaults",
        "snippet_type": "general_snippet",
        "parent_topic": "Object-Oriented Python",
        "main_topic": "OOP Fundamentals",
        "main_week": 4,
        "related_topics": ["OOP Comparison Logic", "Inheritance and Class Relationships"],
        "related_weeks": [4, 6],
        "importance_score": 10,
        "importance_bucket": "highest_value",
        "score_source": "manual_bootstrap",
        "manual_score_reason": "Directly addresses repeated OOP setup errors around `self`, constructor arguments, defaults, and attribute assignment.",
        "pieces": [
            {
                "id": "manual-oop-fundamentals-table",
                "piece_type": "reference_table",
                "title": "Class definition reminders",
                "content": {
                    "headers": ["Pattern", "Meaning", "Trap"],
                    "rows": [
                        ["def __init__(self, x):", "constructor", "`self` must be first parameter"],
                        ["self.x = x", "store instance attribute", "without `self.` the value stays local"],
                        ["obj.method(y)", "normal method call", "do not pass `obj` again"],
                        ["capacity=300", "default argument", "may be omitted by caller"],
                    ],
                },
                "selectable": True,
            },
            {
                "id": "manual-oop-fundamentals-code",
                "piece_type": "code_example",
                "title": "Correct method call",
                "content": {
                    "code": "class Flight:\n    def __init__(self, airline, capacity=300):\n        self.airline = airline\n        self.capacity = capacity\n\n    def set_date(self, date):\n        self.date = date\n\nf = Flight('KLM')\nf.set_date('2026-03-24')",
                    "note": "Python passes `self` automatically when you call `obj.method(...)`.",
                },
                "selectable": True,
            },
        ],
    },
    {
        "id": "manual-oop-comparison",
        "title": "OOP Comparison Logic",
        "snippet_type": "general_snippet",
        "parent_topic": "Object-Oriented Python",
        "main_topic": "OOP Comparison Logic",
        "main_week": 4,
        "related_topics": ["OOP Fundamentals"],
        "related_weeks": [4],
        "importance_score": 7,
        "importance_bucket": "highest_value",
        "score_source": "manual_bootstrap",
        "manual_score_reason": "Supports recurring book-comparison style questions with asymmetric criteria and None fallback.",
        "pieces": [
            {
                "id": "manual-oop-comparison-code",
                "piece_type": "code_example",
                "title": "Asymmetric compare pattern",
                "content": {
                    "code": "def compare(self, other):\n    self_better = self.avg > other.avg and self.reviews >= other.reviews\n    other_better = other.avg > self.avg and other.reviews >= self.reviews\n    if self_better:\n        return self.title\n    if other_better:\n        return other.title\n    return None",
                    "note": "Check both directions explicitly. If neither object beats the other under the rule, return `None`.",
                },
                "selectable": True,
            }
        ],
    },
    {
        "id": "manual-flexible-args-returns-scope",
        "title": "Flexible Arguments, Returns, and Scope",
        "snippet_type": "general_snippet",
        "parent_topic": "Functions and Program Flow",
        "main_topic": "Flexible Arguments and kwargs",
        "main_week": 3,
        "related_topics": ["Scope and Return Behavior", "Functions and Imports"],
        "related_weeks": [3],
        "importance_score": 7,
        "importance_bucket": "highest_value",
        "score_source": "manual_bootstrap",
        "manual_score_reason": "Covers repeated weak questions around *args, **kwargs, tuple returns, implicit None, and local vs global names.",
        "pieces": [
            {
                "id": "manual-flexible-args-returns-scope-table",
                "piece_type": "reference_table",
                "title": "Function signature and return patterns",
                "content": {
                    "headers": ["Goal", "Pattern", "Example"],
                    "rows": [
                        ["collect extra positional args", "def f(*args):", "sum(args)"],
                        ["collect extra keyword args", "def f(**kwargs):", "kwargs['x']"],
                        ["return multiple values", "return a, b", "x, y = f()"],
                        ["implicit None", "function reaches end without return", "value becomes None"],
                        ["local name", "assigned inside function", "not visible outside unless returned"],
                    ],
                },
                "selectable": True,
            },
            {
                "id": "manual-flexible-args-returns-scope-explain",
                "piece_type": "explanation",
                "title": "Return and scope reminder",
                "content": {
                    "text": "Use `return` to send values back to the caller. Printing is not the same as returning. Names assigned inside a function are local unless declared otherwise.",
                },
                "selectable": True,
            },
        ],
    },
    {
        "id": "manual-inheritance",
        "title": "Inheritance and Class Relationships",
        "snippet_type": "general_snippet",
        "parent_topic": "Object-Oriented Python",
        "main_topic": "Inheritance and Class Relationships",
        "main_week": 6,
        "related_topics": ["OOP Fundamentals"],
        "related_weeks": [4, 6],
        "importance_score": 7,
        "importance_bucket": "highest_value",
        "score_source": "manual_bootstrap",
        "manual_score_reason": "This is the clearest genuinely thin topic from the weak-question sample and needs explicit coverage.",
        "pieces": [
            {
                "id": "manual-inheritance-table",
                "piece_type": "reference_table",
                "title": "Inheritance basics",
                "content": {
                    "headers": ["Pattern", "Meaning", "Example"],
                    "rows": [
                        ["class Child(Parent):", "Child inherits from Parent", "class Dog(Animal):"],
                        ["super().__init__(...)", "call parent constructor", "super().__init__(name)"],
                        ["isinstance(x, Parent)", "child object still counts as parent", "isinstance(dog, Animal)"],
                    ],
                },
                "selectable": True,
            },
            {
                "id": "manual-inheritance-code",
                "piece_type": "code_example",
                "title": "Subclass constructor",
                "content": {
                    "code": "class Animal:\n    def __init__(self, name):\n        self.name = name\n\nclass Dog(Animal):\n    def __init__(self, name, breed):\n        super().__init__(name)\n        self.breed = breed",
                    "note": "Use `super()` when the child must keep the parent's initialization logic.",
                },
                "selectable": True,
            },
        ],
    },
]
