from __future__ import annotations

from typing import Any


MANUAL_SNIPPETS_PART1: list[dict[str, Any]] = [
    {
        "id": "manual-essential-string-methods",
        "title": "Essential String Methods and Indexing",
        "snippet_type": "general_snippet",
        "parent_topic": "Strings and Output",
        "main_topic": "String Operations and Methods",
        "main_week": 4,
        "related_topics": ["String Fundamentals", "Output Formatting"],
        "related_weeks": [1, 4],
        "importance_score": 10,
        "importance_bucket": "highest_value",
        "score_source": "manual_bootstrap",
        "manual_score_reason": "Core reference for recurring weak string questions across indexing, slicing, split/join, replace, and search.",
        "pieces": [
            {
                "id": "manual-essential-string-methods-table",
                "piece_type": "reference_table",
                "title": "String methods and indexing quick reference",
                "content": {
                    "headers": ["Pattern", "Meaning", "Example"],
                    "rows": [
                        ["s[i]", "single character", "name[-1]"],
                        ["s[a:b]", "start inclusive, stop exclusive", "name[1:4]"],
                        ["s[::-1]", "reverse copy", "name[::-1]"],
                        ["s.split(',')", "split into list", "'a,b'.split(',')"],
                        ["','.join(lst)", "join strings into one string", "','.join(['a', 'b'])"],
                        ["s.replace(old, new)", "return new string with replacements", "'a-a'.replace('-', '+')"],
                        ["s.find(x)", "index or -1 when missing", "'abc'.find('z')"],
                        ["s.index(x)", "index or ValueError when missing", "'abc'.index('a')"],
                        ["s.strip()", "remove edge whitespace", "' hi '.strip()"],
                        ["s.lower()", "return lowercase copy", "'Hi'.lower()"],
                    ],
                },
                "selectable": True,
            },
            {
                "id": "manual-essential-string-methods-explain",
                "piece_type": "explanation",
                "title": "Fast exam reminders",
                "content": {
                    "text": "Strings are immutable: methods like `replace`, `strip`, and `lower` return a new string. Negative indexes count from the end. Use `find` when missing substrings should give `-1`; use `index` only when you know the substring exists.",
                },
                "selectable": True,
            },
        ],
    },
    {
        "id": "manual-output-formatting",
        "title": "Output Formatting and String Construction",
        "snippet_type": "general_snippet",
        "parent_topic": "Strings and Output",
        "main_topic": "Output Formatting",
        "main_week": 4,
        "related_topics": ["String Operations and Methods", "String Fundamentals"],
        "related_weeks": [4],
        "importance_score": 7,
        "importance_bucket": "highest_value",
        "score_source": "manual_bootstrap",
        "manual_score_reason": "Fills recurring output-shape and formatting gaps in f-strings, .format, separators, and custom wording.",
        "pieces": [
            {
                "id": "manual-output-formatting-table",
                "piece_type": "reference_table",
                "title": "Formatting patterns",
                "content": {
                    "headers": ["Goal", "Pattern", "Example"],
                    "rows": [
                        ["embed value", "f'{x}'", "f'{name} studies Python'"],
                        ["fixed decimals", "f'{x:.2f}'", "f'{price:.2f}'"],
                        ["zero padding", "f'{n:04d}'", "f'{7:04d}' -> 0007"],
                        ["comma join", "', '.join(lst)", "', '.join(['a', 'b'])"],
                        ["custom tail", "head + ', and ' + tail", "items[:-1] + last item"],
                        ["legacy format", "'{:04d}'.format(n)", "'{:04d}'.format(7)"],
                    ],
                },
                "selectable": True,
            },
            {
                "id": "manual-output-formatting-code",
                "piece_type": "code_example",
                "title": "Join plus custom wording",
                "content": {
                    "code": "names = ['Ada', 'Linus', 'Grace']\nprint(', '.join(names[:-1]) + ', and ' + names[-1])",
                    "note": "Use `join` for the repeating part and manual concatenation for the last custom segment.",
                },
                "selectable": True,
            },
        ],
    },
    {
        "id": "manual-iteration-helpers",
        "title": "Iteration Helpers and Operator Traps",
        "snippet_type": "general_snippet",
        "parent_topic": "Collections and Iteration",
        "main_topic": "Loops",
        "main_week": 2,
        "related_topics": ["Lists and Sets", "Operators and Truth"],
        "related_weeks": [1, 2],
        "importance_score": 10,
        "importance_bucket": "highest_value",
        "score_source": "manual_bootstrap",
        "manual_score_reason": "High-yield reference for repeated zip/enumerate/membership/floor-division/modulo/boolean-counting questions.",
        "pieces": [
            {
                "id": "manual-iteration-helpers-table",
                "piece_type": "reference_table",
                "title": "Loop helpers and operator traps",
                "content": {
                    "headers": ["Pattern", "Use", "Exam trap"],
                    "rows": [
                        ["enumerate(x)", "index and value together", "returns `(index, value)` pairs"],
                        ["zip(a, b)", "iterate in parallel", "stops at shortest iterable"],
                        ["x in seq", "membership test", "for dicts this checks keys"],
                        ["a / b", "true division", "always float"],
                        ["a // b", "floor division", "rounds down, not toward zero"],
                        ["a % b", "remainder", "paired with `//`"],
                        ["sum(cond for ...)", "count True values", "`True` counts as 1, `False` as 0"],
                    ],
                },
                "selectable": True,
            },
            {
                "id": "manual-iteration-helpers-code",
                "piece_type": "code_example",
                "title": "Counting matching values",
                "content": {
                    "code": "nums = [2, 5, 8, 9]\ncount = sum(x % 2 != 0 for x in nums)\nprint(count)  # 2",
                    "note": "Use `sum(...)` over boolean comparisons to count matches quickly.",
                },
                "selectable": True,
            },
        ],
    },
    {
        "id": "manual-comprehension-syntax",
        "title": "Comprehension Syntax Reference",
        "snippet_type": "general_snippet",
        "parent_topic": "Collections and Iteration",
        "main_topic": "Comprehensions",
        "main_week": 6,
        "related_topics": ["Lists and Sets", "Dictionaries and Mappings"],
        "related_weeks": [2, 6],
        "importance_score": 10,
        "importance_bucket": "highest_value",
        "score_source": "manual_bootstrap",
        "manual_score_reason": "Directly addresses repeated failures caused by not recognizing comprehension syntax quickly enough.",
        "pieces": [
            {
                "id": "manual-comprehension-syntax-table",
                "piece_type": "reference_table",
                "title": "List, set, and dict comprehension templates",
                "content": {
                    "headers": ["Type", "Template", "Example"],
                    "rows": [
                        ["list", "[expr for x in xs]", "[x * 2 for x in xs]"],
                        ["list + filter", "[expr for x in xs if cond]", "[x for x in xs if x > 0]"],
                        ["list + if/else", "[a if cond else b for x in xs]", "[x if x > 0 else 0 for x in xs]"],
                        ["set", "{expr for x in xs}", "{x % 3 for x in xs}"],
                        ["dict", "{k: v for x in xs}", "{x: len(x) for x in words}"],
                    ],
                },
                "selectable": True,
            },
            {
                "id": "manual-comprehension-syntax-explain",
                "piece_type": "explanation",
                "title": "Placement rule",
                "content": {
                    "text": "The final `if` in a comprehension filters items. The inline `a if cond else b` changes the produced value. For dict comprehensions, the `key: value` pair comes before `for`.",
                },
                "selectable": True,
            },
        ],
    },
    {
        "id": "manual-dictionary-patterns",
        "title": "Dictionary Construction and Iteration Patterns",
        "snippet_type": "general_snippet",
        "parent_topic": "Collections and Iteration",
        "main_topic": "Dictionaries and Mappings",
        "main_week": 2,
        "related_topics": ["Comprehensions", "Lists and Sets"],
        "related_weeks": [2, 6],
        "importance_score": 10,
        "importance_bucket": "highest_value",
        "score_source": "manual_bootstrap",
        "manual_score_reason": "High-yield dictionary reference spanning creation, iteration, equality, and counting patterns.",
        "pieces": [
            {
                "id": "manual-dictionary-patterns-table",
                "piece_type": "reference_table",
                "title": "Dictionary patterns",
                "content": {
                    "headers": ["Goal", "Pattern", "Example"],
                    "rows": [
                        ["zip keys and values", "dict(zip(keys, values))", "dict(zip(a, b))"],
                        ["iterate keys", "for k in d", "for k in d:"],
                        ["iterate items", "for k, v in d.items()", "for k, v in d.items():"],
                        ["values total", "sum(d.values())", "sum(scores.values())"],
                        ["count occurrences", "d[x] = d.get(x, 0) + 1", "counts[word] = counts.get(word, 0) + 1"],
                        ["dict comprehension", "{k: expr for ...}", "{x: len(x) for x in words}"],
                    ],
                },
                "selectable": True,
            },
            {
                "id": "manual-dictionary-patterns-explain",
                "piece_type": "explanation",
                "title": "Equality and ordering reminder",
                "content": {
                    "text": "Dictionary equality ignores insertion order. Membership checks keys by default. Use sorted traversal only when the output order matters.",
                },
                "selectable": True,
            },
        ],
    },
    {
        "id": "manual-pandas-selection",
        "title": "Pandas Selection and Indexing Rules",
        "snippet_type": "general_snippet",
        "parent_topic": "Pandas Data Work",
        "main_topic": "Inspecting and Selecting Data",
        "main_week": 5,
        "related_topics": ["Pandas Core Structures", "Working With Values"],
        "related_weeks": [5],
        "importance_score": 10,
        "importance_bucket": "highest_value",
        "score_source": "manual_bootstrap",
        "manual_score_reason": "Covers the clearest repeated pandas weakness: valid vs invalid selection, loc/iloc, row+column access, and boolean filtering.",
        "pieces": [
            {
                "id": "manual-pandas-selection-table",
                "piece_type": "reference_table",
                "title": "Valid pandas selection forms",
                "content": {
                    "headers": ["Pattern", "Meaning", "Note"],
                    "rows": [
                        ["df['A']", "single column", "Series"],
                        ["df[['A', 'B']]", "multiple columns", "DataFrame"],
                        ["df.loc[2:4, ['A']]", "label-based rows and columns", "stop label included"],
                        ["df.iloc[1:4, [0]]", "position-based rows and columns", "stop index excluded"],
                        ["df[df['A'] > 0]", "boolean row filter", "mask must be boolean"],
                        ["df[row, col]", "invalid shortcut", "switch to `.loc` or `.iloc`"],
                    ],
                },
                "selectable": True,
            },
            {
                "id": "manual-pandas-selection-explain",
                "piece_type": "explanation",
                "title": "loc vs iloc rule",
                "content": {
                    "text": "Use `.loc` for labels and `.iloc` for integer positions. Plain `df[...]` is for column selection or a boolean row mask, not two-axis row+column selection.",
                },
                "selectable": True,
            },
        ],
    },
]
